#ifndef 	_PRIVATE_H_
#define 	_PRIVATE_H_

#include "constants.h"
using namespace arma;

int source_ids[SOURCE_COUNT]={
	SOURCE_0_ID,
	SOURCE_1_ID,
	SOURCE_2_ID,
	SOURCE_3_ID,
	SOURCE_4_ID,
	SOURCE_5_ID
};

const char* source_names[SOURCE_COUNT]={
	SOURCE_0_NAME,
	SOURCE_1_NAME,
	SOURCE_2_NAME,
	SOURCE_3_NAME,
	SOURCE_4_NAME,
	SOURCE_5_NAME
};

const char* source_devnames[SOURCE_COUNT]={
	SOURCE_0_DEVNAME,
	SOURCE_1_DEVNAME,
	SOURCE_2_DEVNAME,
	SOURCE_3_DEVNAME,
	SOURCE_4_DEVNAME,
	SOURCE_5_DEVNAME
};

unsigned int source_x[SOURCE_COUNT]={
	SOURCE_0_X,
	SOURCE_1_X,
	SOURCE_2_X,
	SOURCE_3_X,
	SOURCE_4_X,
	SOURCE_5_X
};

unsigned int source_y[SOURCE_COUNT]={
	SOURCE_0_Y,
	SOURCE_1_Y,
	SOURCE_2_Y,
	SOURCE_3_Y,
	SOURCE_4_Y,
	SOURCE_5_Y
};

vec source_transp[SOURCE_COUNT]={
	colvec({SOURCE_0_TRANSP_X, SOURCE_0_TRANSP_Y, SOURCE_0_TRANSP_Z}),
	colvec({SOURCE_1_TRANSP_X, SOURCE_1_TRANSP_Y, SOURCE_1_TRANSP_Z}),
	colvec({SOURCE_2_TRANSP_X, SOURCE_2_TRANSP_Y, SOURCE_2_TRANSP_Z}),
	colvec({SOURCE_3_TRANSP_X, SOURCE_3_TRANSP_Y, SOURCE_3_TRANSP_Z}),
	colvec({SOURCE_4_TRANSP_X, SOURCE_4_TRANSP_Y, SOURCE_4_TRANSP_Z}),
	colvec({SOURCE_5_TRANSP_X, SOURCE_5_TRANSP_Y, SOURCE_5_TRANSP_Z})
};

vec source_rotate[SOURCE_COUNT]={
	colvec({SOURCE_0_ROTATE_X, SOURCE_0_ROTATE_Y, SOURCE_0_ROTATE_Z}),
	colvec({SOURCE_1_ROTATE_X, SOURCE_1_ROTATE_Y, SOURCE_1_ROTATE_Z}),
	colvec({SOURCE_2_ROTATE_X, SOURCE_2_ROTATE_Y, SOURCE_2_ROTATE_Z}),
	colvec({SOURCE_3_ROTATE_X, SOURCE_3_ROTATE_Y, SOURCE_3_ROTATE_Z}),
	colvec({SOURCE_4_ROTATE_X, SOURCE_4_ROTATE_Y, SOURCE_4_ROTATE_Z}),
	colvec({SOURCE_5_ROTATE_X, SOURCE_5_ROTATE_Y, SOURCE_5_ROTATE_Z})
};

/*Planes*/
int plane_ids[PLANE_COUNT]={
	PLANE_0_ID,
	PLANE_1_ID,
	PLANE_2_ID,
	PLANE_3_ID,
	PLANE_4_ID,
	PLANE_5_ID,
	PLANE_6_ID,
	PLANE_7_ID,
	PLANE_8_ID,
	PLANE_9_ID,
	PLANE_10_ID,
	PLANE_11_ID
};

int plane_source_id[PLANE_COUNT]={
	PLANE_0_SOURCEID,
	PLANE_1_SOURCEID,
	PLANE_2_SOURCEID,
	PLANE_3_SOURCEID,
	PLANE_4_SOURCEID,
	PLANE_5_SOURCEID,
	PLANE_6_SOURCEID,
	PLANE_7_SOURCEID,
	PLANE_8_SOURCEID,
	PLANE_9_SOURCEID,
	PLANE_10_SOURCEID,
	PLANE_11_SOURCEID
};

vec plane_dots[PLANE_COUNT][3]={
	{
		{colvec({PLANE_0_DOT_0_X, PLANE_0_DOT_0_Y, PLANE_0_DOT_0_Z})},
		{colvec({PLANE_0_DOT_1_X, PLANE_0_DOT_1_Y, PLANE_0_DOT_1_Z})},
		{colvec({PLANE_0_DOT_2_X, PLANE_0_DOT_2_Y, PLANE_0_DOT_2_Z})},
	},
	{
		{colvec({PLANE_1_DOT_0_X, PLANE_1_DOT_0_Y, PLANE_1_DOT_0_Z})},
		{colvec({PLANE_1_DOT_1_X, PLANE_1_DOT_1_Y, PLANE_1_DOT_1_Z})},
		{colvec({PLANE_1_DOT_2_X, PLANE_1_DOT_2_Y, PLANE_1_DOT_2_Z})},
	},
	{
		{colvec({PLANE_2_DOT_0_X, PLANE_2_DOT_0_Y, PLANE_2_DOT_0_Z})},
		{colvec({PLANE_2_DOT_1_X, PLANE_2_DOT_1_Y, PLANE_2_DOT_1_Z})},
		{colvec({PLANE_2_DOT_2_X, PLANE_2_DOT_2_Y, PLANE_2_DOT_2_Z})},
	},
	{
		{colvec({PLANE_3_DOT_0_X, PLANE_3_DOT_0_Y, PLANE_3_DOT_0_Z})},
		{colvec({PLANE_3_DOT_1_X, PLANE_3_DOT_1_Y, PLANE_3_DOT_1_Z})},
		{colvec({PLANE_3_DOT_2_X, PLANE_3_DOT_2_Y, PLANE_3_DOT_2_Z})},
	},
	{
		{colvec({PLANE_4_DOT_0_X, PLANE_4_DOT_0_Y, PLANE_4_DOT_0_Z})},
		{colvec({PLANE_4_DOT_1_X, PLANE_4_DOT_1_Y, PLANE_4_DOT_1_Z})},
		{colvec({PLANE_4_DOT_2_X, PLANE_4_DOT_2_Y, PLANE_4_DOT_2_Z})},
	},
	{
		{colvec({PLANE_5_DOT_0_X, PLANE_5_DOT_0_Y, PLANE_5_DOT_0_Z})},
		{colvec({PLANE_5_DOT_1_X, PLANE_5_DOT_1_Y, PLANE_5_DOT_1_Z})},
		{colvec({PLANE_5_DOT_2_X, PLANE_5_DOT_2_Y, PLANE_5_DOT_2_Z})},
	},
	{
		{colvec({PLANE_6_DOT_0_X, PLANE_6_DOT_0_Y, PLANE_6_DOT_0_Z})},
		{colvec({PLANE_6_DOT_1_X, PLANE_6_DOT_1_Y, PLANE_6_DOT_1_Z})},
		{colvec({PLANE_6_DOT_2_X, PLANE_6_DOT_2_Y, PLANE_6_DOT_2_Z})},
	},
	{
		{colvec({PLANE_7_DOT_0_X, PLANE_7_DOT_0_Y, PLANE_7_DOT_0_Z})},
		{colvec({PLANE_7_DOT_1_X, PLANE_7_DOT_1_Y, PLANE_7_DOT_1_Z})},
		{colvec({PLANE_7_DOT_2_X, PLANE_7_DOT_2_Y, PLANE_7_DOT_2_Z})},
	},
	{
		{colvec({PLANE_8_DOT_0_X, PLANE_8_DOT_0_Y, PLANE_8_DOT_0_Z})},
		{colvec({PLANE_8_DOT_1_X, PLANE_8_DOT_1_Y, PLANE_8_DOT_1_Z})},
		{colvec({PLANE_8_DOT_2_X, PLANE_8_DOT_2_Y, PLANE_8_DOT_2_Z})},
	},
	{
		{colvec({PLANE_9_DOT_0_X, PLANE_9_DOT_0_Y, PLANE_9_DOT_0_Z})},
		{colvec({PLANE_9_DOT_1_X, PLANE_9_DOT_1_Y, PLANE_9_DOT_1_Z})},
		{colvec({PLANE_9_DOT_2_X, PLANE_9_DOT_2_Y, PLANE_9_DOT_2_Z})},
	},
	{
		{colvec({PLANE_10_DOT_0_X, PLANE_10_DOT_0_Y, PLANE_10_DOT_0_Z})},
		{colvec({PLANE_10_DOT_1_X, PLANE_10_DOT_1_Y, PLANE_10_DOT_1_Z})},
		{colvec({PLANE_10_DOT_2_X, PLANE_10_DOT_2_Y, PLANE_10_DOT_2_Z})},
	},
	{
		{colvec({PLANE_11_DOT_0_X, PLANE_11_DOT_0_Y, PLANE_11_DOT_0_Z})},
		{colvec({PLANE_11_DOT_1_X, PLANE_11_DOT_1_Y, PLANE_11_DOT_1_Z})},
		{colvec({PLANE_11_DOT_2_X, PLANE_11_DOT_2_Y, PLANE_11_DOT_2_Z})},
	}
};

vec plane_scale[PLANE_COUNT]={
	colvec({PLANE_0_SCALE_X,PLANE_0_SCALE_Y}),
	colvec({PLANE_1_SCALE_X,PLANE_1_SCALE_Y}),
	colvec({PLANE_2_SCALE_X,PLANE_2_SCALE_Y}),
	colvec({PLANE_3_SCALE_X,PLANE_3_SCALE_Y}),
	colvec({PLANE_4_SCALE_X,PLANE_4_SCALE_Y}),
	colvec({PLANE_5_SCALE_X,PLANE_5_SCALE_Y}),
	colvec({PLANE_6_SCALE_X,PLANE_6_SCALE_Y}),
	colvec({PLANE_7_SCALE_X,PLANE_7_SCALE_Y}),
	colvec({PLANE_8_SCALE_X,PLANE_8_SCALE_Y}),
	colvec({PLANE_9_SCALE_X,PLANE_9_SCALE_Y}),
	colvec({PLANE_10_SCALE_X,PLANE_10_SCALE_Y}),
	colvec({PLANE_11_SCALE_X,PLANE_11_SCALE_Y})
};

vec plane_offset[PLANE_COUNT]={
	colvec({PLANE_0_OFFSET_X,PLANE_0_OFFSET_Y}),
	colvec({PLANE_1_OFFSET_X,PLANE_1_OFFSET_Y}),
	colvec({PLANE_2_OFFSET_X,PLANE_2_OFFSET_Y}),
	colvec({PLANE_3_OFFSET_X,PLANE_3_OFFSET_Y}),
	colvec({PLANE_4_OFFSET_X,PLANE_4_OFFSET_Y}),
	colvec({PLANE_5_OFFSET_X,PLANE_5_OFFSET_Y}),
	colvec({PLANE_6_OFFSET_X,PLANE_6_OFFSET_Y}),
	colvec({PLANE_7_OFFSET_X,PLANE_7_OFFSET_Y}),
	colvec({PLANE_8_OFFSET_X,PLANE_8_OFFSET_Y}),
	colvec({PLANE_9_OFFSET_X,PLANE_9_OFFSET_Y}),
	colvec({PLANE_10_OFFSET_X,PLANE_10_OFFSET_Y}),
	colvec({PLANE_11_OFFSET_X,PLANE_11_OFFSET_Y})
};

#endif